[deploy]
bucket = 'cfn-artifacts-karthik'
region = 'us-east-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'karthikmurali60'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''
